# Módulo 2 - Manipulação de Dados com Pandas

**Curso:** Python para Ciência de Dados  
**Objetivo:** introduzir leitura, limpeza e manipulação básica de dados com Pandas.  
**Datasets usados:** `EquipeA_escola.csv` e `EquipeE_cidades.csv`.

---
## 1. Preparação do ambiente

Neste módulo, vamos trabalhar com tabelas. O Pandas organiza os dados em estruturas chamadas **Series** e **DataFrames**.

In [1]:
import pandas as pd

# Caminhos relativos ao notebook
CAMINHO_ESCOLA = '../../datasets/escolhidos_ava_2/EquipeA_escola.csv'
CAMINHO_CIDADES = '../../datasets/escolhidos_ava_2/EquipeE_cidades.csv'

---
## 2. Primeiro contato com um DataFrame

Começamos com o dataset da escola, que é pequeno e ideal para entender os comandos básicos.

In [2]:
# Leitura do CSV mais simples
df_escola = pd.read_csv(CAMINHO_ESCOLA)
df_escola

       nome  nota  frequencia
0       Ana   9.0          95
1     Bruno   7.5          80
2     Carol   8.0          88
3     Diego   6.5          70
4     Elisa   9.5         100
5     Fabio   5.0          60
6  Giovanna   8.2          90
7    Heitor   4.5          45
8      Igor   7.8          82
9     Julia  10.0          98

In [3]:
# Observando dimensões, tipos e estatísticas iniciais
print('Linhas e colunas:', df_escola.shape)
print('\nTipos de dados:')
print(df_escola.dtypes)
print('\nResumo numérico:')
display(df_escola.describe())

Linhas e colunas: (10, 3)

Tipos de dados:
nome              str
nota          float64
frequencia      int64
dtype: object

Resumo numérico:

           nota  frequencia
count  10.00000   10.000000
mean    7.60000   80.800000
std     1.80985   17.750117
min     4.50000   45.000000
25%     6.75000   72.500000
50%     7.90000   85.000000
75%     8.80000   93.750000
max    10.00000  100.000000

---
## 3. Seleção de colunas e filtros

Uma das tarefas mais comuns em análise de dados é selecionar partes da tabela.

In [4]:
# Selecionando colunas específicas
df_escola[['nome', 'nota']]

       nome  nota
0       Ana   9.0
1     Bruno   7.5
2     Carol   8.0
3     Diego   6.5
4     Elisa   9.5
5     Fabio   5.0
6  Giovanna   8.2
7    Heitor   4.5
8      Igor   7.8
9     Julia  10.0

In [5]:
# Filtrando alunos com nota maior ou igual a 8
df_escola[df_escola['nota'] >= 8]

       nome  nota  frequencia
0       Ana   9.0          95
2     Carol   8.0          88
4     Elisa   9.5         100
6  Giovanna   8.2          90
9     Julia  10.0          98

In [6]:
# Filtrando alunos aprovados considerando nota e frequência
aprovados = df_escola[(df_escola['nota'] >= 7) & (df_escola['frequencia'] >= 75)]
aprovados

       nome  nota  frequencia
0       Ana   9.0          95
1     Bruno   7.5          80
2     Carol   8.0          88
4     Elisa   9.5         100
6  Giovanna   8.2          90
8      Igor   7.8          82
9     Julia  10.0          98

---
## 4. Criando novas colunas

Transformar dados também envolve criar colunas com regras simples.

In [7]:
# Classificando a situação de cada aluno
df_escola['situacao'] = df_escola.apply(
    lambda linha: 'Aprovado' if linha['nota'] >= 7 and linha['frequencia'] >= 75 else 'Reprovado',
    axis=1
)
df_escola

       nome  nota  frequencia   situacao
0       Ana   9.0          95   Aprovado
1     Bruno   7.5          80   Aprovado
2     Carol   8.0          88   Aprovado
3     Diego   6.5          70  Reprovado
4     Elisa   9.5         100   Aprovado
5     Fabio   5.0          60  Reprovado
6  Giovanna   8.2          90   Aprovado
7    Heitor   4.5          45  Reprovado
8      Igor   7.8          82   Aprovado
9     Julia  10.0          98   Aprovado

In [8]:
# Estatísticas por situação
df_escola.groupby('situacao')[['nota', 'frequencia']].mean().round(2)

           nota  frequencia
situacao
Aprovado   8.57       90.43
Reprovado  5.33       58.33

---
## 5. Limpeza de dados

Mesmo quando um dataset parece pronto, vale conferir duplicatas, valores ausentes e nomes de colunas.

In [9]:
# Verificações simples de qualidade dos dados
print('Valores ausentes por coluna:')
print(df_escola.isna().sum())
print('\nLinhas duplicadas:', df_escola.duplicated().sum())

Valores ausentes por coluna:
nome          0
nota          0
frequencia    0
situacao      0
dtype: int64

Linhas duplicadas: 0

In [10]:
# Exemplo didático de limpeza: padronizando nomes de colunas
df_escola_limpo = df_escola.rename(columns={
    'nome': 'aluno',
    'nota': 'nota_final',
    'frequencia': 'frequencia_percentual'
})
df_escola_limpo.head()

   aluno  nota_final  frequencia_percentual   situacao
0    Ana         9.0                     95   Aprovado
1  Bruno         7.5                     80   Aprovado
2  Carol         8.0                     88   Aprovado
3  Diego         6.5                     70  Reprovado
4  Elisa         9.5                    100   Aprovado

---
## 6. Avançando para um dataset maior

Agora usamos `EquipeE_cidades.csv`, que possui muitas colunas e permite análises mais próximas de um contexto real.

In [11]:
# Lendo apenas parte do dataset para um primeiro reconhecimento
df_cidades = pd.read_csv(CAMINHO_CIDADES)
print('Formato:', df_cidades.shape)
display(df_cidades.head())

Formato: (5578, 81)

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,...,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876,6876,0,2137,1546,591,5300,...,0,0,0,2158,1246,0,0,0,0,1
1,Abadia Dos Dourados,MG,0,6704,6704,0,2328,1481,847,4154,...,0,0,0,2227,1142,0,0,0,0,1
2,Abadiânia,GO,0,15757,15609,148,4655,3233,1422,10656,...,1,33724584,67091904,2838,1426,0,0,0,0,3
3,Abaetetuba,PA,0,141100,141040,60,31061,19057,12004,82956,...,4,76181384,800078483,5277,25661,0,0,0,0,2
4,Abaeté,MG,0,22690,22690,0,7694,6667,1027,18464,...,2,44974716,371922572,6928,2953,0,0,0,0,4

In [12]:
# Selecionando um subconjunto mais amigável para começar a análise
colunas_principais = [
    'CITY', 'STATE', 'CAPITAL', 'ESTIMATED_POP', 'GDP_CAPITA',
    'IDHM', 'HOTELS', 'BEDS', 'Cars', 'Motorcycles', 'RURAL_URBAN'
]
cidades_base = df_cidades[colunas_principais].copy()
cidades_base.head()

,CITY,STATE,CAPITAL,ESTIMATED_POP,GDP_CAPITA,IDHM,HOTELS,BEDS,Cars,Motorcycles,RURAL_URBAN
0,Abadia De Goiás,GO,0,8583,20665.0,0.708,0,0,2158,1246,Urbano
1,Abadia Dos Dourados,MG,0,6972,25592.0,0.689,0,0,2227,1142,Rural Adjacente
2,Abadiânia,GO,0,19614,15628.0,0.689,1,34,2838,1426,Rural Adjacente
3,Abaetetuba,PA,0,156292,8222.0,0.628,0,0,5277,25661,Urbano
4,Abaeté,MG,0,23223,18250.0,0.698,0,0,6928,2953,Urbano

In [13]:
# Investigando valores ausentes e tipos
print(cidades_base.isna().sum())
print('\nTipos de dados:')
print(cidades_base.dtypes)

CITY             0
STATE            0
CAPITAL          0
ESTIMATED_POP    0
GDP_CAPITA       0
IDHM             0
HOTELS           0
BEDS             0
Cars             0
Motorcycles      0
RURAL_URBAN      0
dtype: int64

Tipos de dados:
CITY                 str
STATE                str
CAPITAL            int64
ESTIMATED_POP      int64
GDP_CAPITA       float64
IDHM             float64
HOTELS             int64
BEDS               int64
Cars               int64
Motorcycles        int64
RURAL_URBAN          str
dtype: object

In [14]:
# Exemplos de filtros úteis
capitais = cidades_base[cidades_base['CAPITAL'] == 1]
cidades_turisticas = cidades_base[cidades_base['HOTELS'] > 20]
display(capitais[['CITY', 'STATE', 'IDHM', 'GDP_CAPITA']].head())
display(cidades_turisticas[['CITY', 'STATE', 'HOTELS', 'BEDS']].head(10))

               CITY STATE   IDHM  GDP_CAPITA
256         Aracaju    SE  0.770     25718.0
550  Belo Horizonte    MG  0.810     35122.0
557           Belém    PB  0.592      8744.0
558           Belém    PA  0.746     20350.0
559           Belém    AL  0.593      8037.0

                CITY STATE  HOTELS  BEDS
550   Belo Horizonte    MG      29  5075
719         Brasília    DF      23  4960
1458        Curitiba    PR      23  3157
1773   Florianópolis    SC      21  2954
1793       Fortaleza    CE      32  3135
1801   Foz Do Iguaçu    PR      28  2652
1921         Gramado    RS      31  2166
2130   Ilha Comprida    SP      46  3053
2205         Ipojuca    PE      33  1454
2263         Itacaré    BA      23   780

In [15]:
# Ordenando para responder perguntas simples
top_gdp = cidades_base.nlargest(10, 'GDP_CAPITA')[['CITY', 'STATE', 'GDP_CAPITA']]
top_pop = cidades_base.nlargest(10, 'ESTIMATED_POP')[['CITY', 'STATE', 'ESTIMATED_POP']]
display(top_gdp)
display(top_pop)

                        CITY STATE  GDP_CAPITA
3644                Paulínia    SP    314638.0
4584                Selvíria    MS    306139.0
4786  São Francisco Do Conde    BA    296459.0
5256                 Triunfo    RS    289932.0
732             Brejo Alegre    SP    274572.0
4576  Sebastianópolis Do Sul    SP    253147.0
2766                Louveira    SP    250827.0
950          Campos De Júlio    MT    202309.0
3011               Meridiano    SP    184603.0
1698                 Extrema    MG    183218.0

                CITY STATE  ESTIMATED_POP
4997       São Paulo    SP       12176866
4175  Rio De Janeiro    RJ        6688927
719         Brasília    DF        2974703
4300        Salvador    BA        2857329
1793       Fortaleza    CE        2643247
550   Belo Horizonte    MG        2501576
2849          Manaus    AM        2145444
1458        Curitiba    PR        1917185
4078          Recife    PE        1637834
1900         Goiânia    GO        1495705

In [16]:
# Resumo por estado: média de IDHM e PIB per capita
resumo_estado = (
    cidades_base.groupby('STATE')[['IDHM', 'GDP_CAPITA']]
    .mean()
    .sort_values('IDHM', ascending=False)
    .round(3)
)
resumo_estado.head(10)

        IDHM  GDP_CAPITA
STATE
DF     0.824   79100.000
SP     0.740   32174.187
SC     0.727   30630.298
RS     0.709   33590.038
RJ     0.709   30850.323
PR     0.702   29169.958
GO     0.695   26278.805
ES     0.692   21217.526
MT     0.684   36405.057
MS     0.671   37003.823

---
## 7. Fechamento

Neste notebook você viu:
- como ler CSVs com Pandas;
- como filtrar, selecionar e ordenar dados;
- como criar colunas derivadas;
- como iniciar uma limpeza e um reconhecimento de datasets maiores.

No notebook prático do módulo 2, a ideia é repetir esse fluxo com mais autonomia.