# Módulo 2 - Prática Guiada de Manipulação de Dados

Este notebook foi montado de forma **totalmente comentada** para servir como material de prática.

---
## 1. Carregando os dados

Vamos trabalhar com os dois datasets do módulo: um pequeno para consolidar a base e outro maior para treinar um fluxo mais realista.

In [1]:
import pandas as pd

df_escola = pd.read_csv('../../datasets/escolhidos_ava_2/EquipeA_escola.csv')
df_cidades = pd.read_csv('../../datasets/escolhidos_ava_2/EquipeE_cidades.csv')

In [2]:
# Sempre vale começar olhando as primeiras linhas.
# Isso ajuda a reconhecer o que cada coluna representa.
display(df_escola.head())
display(df_cidades.head(3))

    nome  nota  frequencia
0    Ana   9.0          95
1  Bruno   7.5          80
2  Carol   8.0          88
3  Diego   6.5          70
4  Elisa   9.5         100

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,...,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876,6876,0,2137,1546,591,5300,...,0,0,0,2158,1246,0,0,0,0,1
1,Abadia Dos Dourados,MG,0,6704,6704,0,2328,1481,847,4154,...,0,0,0,2227,1142,0,0,0,0,1
2,Abadiânia,GO,0,15757,15609,148,4655,3233,1422,10656,...,1,33724584,67091904,2838,1426,0,0,0,0,3

---
## 2. Miniestudo 1: desempenho escolar

Como o dataset é pequeno, conseguimos percorrer todo o ciclo de leitura, transformação e síntese com poucas linhas.

In [3]:
# Criamos uma cópia para evitar alterar o DataFrame original por engano.
escola = df_escola.copy()

# A coluna 'situacao' será usada em várias análises posteriores.
escola['situacao'] = escola.apply(
    lambda linha: 'Aprovado' if linha['nota'] >= 7 and linha['frequencia'] >= 75 else 'Reprovado',
    axis=1
)

# Agora já conseguimos enxergar o resultado da regra de negócio.
escola

       nome  nota  frequencia   situacao
0       Ana   9.0          95   Aprovado
1     Bruno   7.5          80   Aprovado
2     Carol   8.0          88   Aprovado
3     Diego   6.5          70  Reprovado
4     Elisa   9.5         100   Aprovado
5     Fabio   5.0          60  Reprovado
6  Giovanna   8.2          90   Aprovado
7    Heitor   4.5          45  Reprovado
8      Igor   7.8          82   Aprovado
9     Julia  10.0          98   Aprovado

In [4]:
# Resumo rápido do conjunto.
resumo_escola = {
    'media_nota': escola['nota'].mean(),
    'media_frequencia': escola['frequencia'].mean(),
    'quantidade_aprovados': (escola['situacao'] == 'Aprovado').sum(),
    'quantidade_reprovados': (escola['situacao'] == 'Reprovado').sum()
}
resumo_escola

{'media_nota': np.float64(7.6),
 'media_frequencia': np.float64(80.8),
 'quantidade_aprovados': np.int64(7),
 'quantidade_reprovados': np.int64(3)}

In [5]:
# Também podemos ordenar do melhor para o pior desempenho.
ranking_escola = escola.sort_values(['nota', 'frequencia'], ascending=False)
ranking_escola

       nome  nota  frequencia   situacao
9     Julia  10.0          98   Aprovado
4     Elisa   9.5         100   Aprovado
0       Ana   9.0          95   Aprovado
6  Giovanna   8.2          90   Aprovado
2     Carol   8.0          88   Aprovado
8      Igor   7.8          82   Aprovado
1     Bruno   7.5          80   Aprovado
3     Diego   6.5          70  Reprovado
5     Fabio   5.0          60  Reprovado
7    Heitor   4.5          45  Reprovado

---
## 3. Miniestudo 2: cidades brasileiras

O segundo dataset é grande. Por isso, um bom caminho é selecionar primeiro apenas as colunas relevantes para o problema.

In [6]:
# Escolhemos variáveis ligadas a população, renda, mobilidade e turismo.
colunas = [
    'CITY', 'STATE', 'CAPITAL', 'ESTIMATED_POP', 'GDP_CAPITA', 'IDHM',
    'HOTELS', 'BEDS', 'Cars', 'Motorcycles', 'RURAL_URBAN'
]
cidades = df_cidades[colunas].copy()
cidades.head()

,CITY,STATE,CAPITAL,ESTIMATED_POP,GDP_CAPITA,IDHM,HOTELS,BEDS,Cars,Motorcycles,RURAL_URBAN
0,Abadia De Goiás,GO,0,8583,20665.0,0.708,0,0,2158,1246,Urbano
1,Abadia Dos Dourados,MG,0,6972,25592.0,0.689,0,0,2227,1142,Rural Adjacente
2,Abadiânia,GO,0,19614,15628.0,0.689,1,34,2838,1426,Rural Adjacente
3,Abaetetuba,PA,0,156292,8222.0,0.628,0,0,5277,25661,Urbano
4,Abaeté,MG,0,23223,18250.0,0.698,0,0,6928,2953,Urbano

In [7]:
# Renomear colunas pode melhorar muito a leitura de quem está começando.
cidades = cidades.rename(columns={
    'CITY': 'cidade',
    'STATE': 'uf',
    'CAPITAL': 'capital',
    'ESTIMATED_POP': 'populacao_estimada',
    'GDP_CAPITA': 'pib_per_capita',
    'IDHM': 'idhm',
    'HOTELS': 'hoteis',
    'BEDS': 'leitos',
    'Cars': 'carros',
    'Motorcycles': 'motos',
    'RURAL_URBAN': 'perfil_territorial'
})
cidades.head()

,cidade,uf,capital,populacao_estimada,pib_per_capita,idhm,hoteis,leitos,carros,motos,perfil_territorial
0,Abadia De Goiás,GO,0,8583,20665.0,0.708,0,0,2158,1246,Urbano
1,Abadia Dos Dourados,MG,0,6972,25592.0,0.689,0,0,2227,1142,Rural Adjacente
2,Abadiânia,GO,0,19614,15628.0,0.689,1,34,2838,1426,Rural Adjacente
3,Abaetetuba,PA,0,156292,8222.0,0.628,0,0,5277,25661,Urbano
4,Abaeté,MG,0,23223,18250.0,0.698,0,0,6928,2953,Urbano

In [8]:
# Primeiro diagnóstico: há valores ausentes?
cidades.isna().sum()

cidade                0
uf                    0
capital               0
populacao_estimada    0
pib_per_capita        0
idhm                  0
hoteis                0
leitos                0
carros                0
motos                 0
perfil_territorial    0
dtype: int64

In [9]:
# Criando indicadores derivados para facilitar perguntas analíticas.
cidades['tem_rede_hoteleira'] = cidades['hoteis'] > 0
cidades['frota_total'] = cidades['carros'] + cidades['motos']
cidades['faixa_idhm'] = pd.cut(
    cidades['idhm'],
    bins=[0, 0.6, 0.7, 0.8, 1.0],
    labels=['baixo', 'medio', 'alto', 'muito_alto']
)
cidades[['cidade', 'uf', 'idhm', 'faixa_idhm', 'frota_total']].head()

                cidade  uf   idhm faixa_idhm  frota_total
0      Abadia De Goiás  GO  0.708       alto         3404
1  Abadia Dos Dourados  MG  0.689      medio         3369
2            Abadiânia  GO  0.689      medio         4264
3           Abaetetuba  PA  0.628      medio        30938
4               Abaeté  MG  0.698      medio         9881

In [10]:
# Exemplo de pergunta 1: quais são as cidades mais populosas?
mais_populosas = cidades.nlargest(10, 'populacao_estimada')[['cidade', 'uf', 'populacao_estimada']]
mais_populosas

              cidade  uf  populacao_estimada
4997       São Paulo  SP            12176866
4175  Rio De Janeiro  RJ             6688927
719         Brasília  DF             2974703
4300        Salvador  BA             2857329
1793       Fortaleza  CE             2643247
550   Belo Horizonte  MG             2501576
2849          Manaus  AM             2145444
1458        Curitiba  PR             1917185
4078          Recife  PE             1637834
1900         Goiânia  GO             1495705

In [11]:
# Exemplo de pergunta 2: quais estados têm maior média de IDHM?
idhm_por_uf = (
    cidades.groupby('uf')['idhm']
    .mean()
    .sort_values(ascending=False)
    .round(4)
)
idhm_por_uf.head(10)

uf
DF    0.8240
SP    0.7396
SC    0.7267
RS    0.7092
RJ    0.7087
PR    0.7019
GO    0.6950
ES    0.6922
MT    0.6843
MS    0.6711
Name: idhm, dtype: float64

In [12]:
# Exemplo de pergunta 3: capitais têm, em média, IDHM maior?
idhm_capital = cidades.groupby('capital')['idhm'].mean().round(4)
idhm_capital

capital
0    0.6575
1    0.7482
Name: idhm, dtype: float64

In [13]:
# Exemplo de pergunta 4: quais cidades se destacam em turismo?
# Aqui usamos hotéis e leitos como aproximação simples.
turismo = cidades[cidades['hoteis'] > 20].sort_values(['hoteis', 'leitos'], ascending=False)
turismo[['cidade', 'uf', 'hoteis', 'leitos']].head(15)

                      cidade  uf  hoteis  leitos
3819             Pirenópolis  GO      97    2418
4175          Rio De Janeiro  RJ      94   13247
4997               São Paulo  SP      57   10022
2130           Ilha Comprida  SP      46    3053
2849                  Manaus  AM      34    3401
2205                 Ipojuca  PE      33    1454
1793               Fortaleza  CE      32    3135
1921                 Gramado  RS      31    2166
2546  Jijoca De Jericoacoara  CE      31     647
5367                 Urubici  SC      31     583
550           Belo Horizonte  MG      29    5075
1801           Foz Do Iguaçu  PR      28    2652
3544               Paranaguá  PR      26     821
719                 Brasília  DF      23    4960
1458                Curitiba  PR      23    3157

---
## 4. Conclusão prática

Se você conseguir repetir este roteiro sozinho, já domina a base do módulo 2:
- leitura de arquivos;
- seleção de colunas;
- filtros e ordenação;
- criação de colunas;
- agrupamentos simples para responder perguntas.