# Modulo 1 - Fundamentos de Python

Notebook funcional para a primeira aula do curso **Python para Ciencia de Dados**.

## 1. Primeiro codigo

In [1]:
print("Bem-vindo ao curso de Python para Ciencia de Dados!")

Bem-vindo ao curso de Python para Ciencia de Dados!

## 2. Variaveis e tipos de dados

In [2]:
nome = "Carlos"
idade = 22
altura = 1.75
estudante = True

print(type(nome))
print(type(idade))
print(type(altura))
print(type(estudante))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

## 3. Operadores

In [3]:
a = 10
b = 3

print("Soma:", a + b)
print("Subtracao:", a - b)
print("Multiplicacao:", a * b)
print("Divisao:", a / b)
print("a > b:", a > b)
print("a == b:", a == b)

Soma: 13
Subtracao: 7
Multiplicacao: 30
Divisao: 3.3333333333333335
a > b: True
a == b: False

## 4. Condicionais

In [4]:
nota = 7

if nota >= 7:
    print("Aprovado")
else:
    print("Reprovado")

Aprovado

## 5. Lacos de repeticao

In [5]:
for i in range(1, 6):
    print("Numero:", i)

Numero: 1
Numero: 2
Numero: 3
Numero: 4
Numero: 5

## 6. Estruturas de dados

In [6]:
lista_notas = [7.5, 8.0, 6.5, 9.0]
print(lista_notas)

aluno = {
    "nome": "Marina",
    "idade": 19,
    "curso": "Introducao a Ciencia de Dados"
}
print(aluno["nome"])

[7.5, 8.0, 6.5, 9.0]
Marina

## 7. Mini exemplo com dataset simples

In [7]:
import pandas as pd

df = pd.read_csv("../../datasets/exemplos/alunos_desempenho.csv")
df

     nome  idade                     curso  nota_final  frequencia
0     Ana     17  Introducao a Programacao         8.5          90
1   Bruno     18  Introducao a Programacao         6.0          75
2   Carla     17  Introducao a Programacao         9.0          95
3   Diego     19  Introducao a Programacao         5.5          68
4  Elaine     18  Introducao a Programacao         7.5          88

In [8]:
aprovados = df[df["nota_final"] >= 7]
aprovados

     nome  idade                     curso  nota_final  frequencia
0     Ana     17  Introducao a Programacao         8.5          90
2   Carla     17  Introducao a Programacao         9.0          95
4  Elaine     18  Introducao a Programacao         7.5          88

## 8. Encerramento

Neste modulo, voce viu os fundamentos essenciais para avancar para a manipulacao de dados com Pandas.